// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

type Account struct {
	ID             uuid.UUID
	DocumentNumber string
	Name           string
	Secret         string
	Balance        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Transfer struct {
	ID                   uuid.UUID
	AccountOriginID      uuid.UUID
	AccountDestinationID uuid.UUID
	Amount               int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
